/** @type {import('tailwindcss').Config} */
// Tokens ported verbatim from design/design-system/design-system.md ("Recall Productivity").
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'surface-variant': '#e0e3e5',
        secondary: '#515f74',
        'surface-container-highest': '#e0e3e5',
        'tertiary-fixed': '#d8e3fb',
        error: '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#bcc7de',
        'primary-container': '#4338ca',
        'on-secondary-container': '#57657a',
        'primary-fixed-dim': '#c3c0ff',
        outline: '#777586',
        'surface-container-low': '#f2f4f6',
        'on-surface-variant': '#464554',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#111c2d',
        'on-primary-fixed': '#100069',
        'inverse-on-surface': '#eff1f3',
        'secondary-container': '#d5e3fc',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#3c475a',
        tertiary: '#303b4e',
        'surface-container': '#eceef0',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'on-surface': '#191c1e',
        'on-primary-container': '#c1beff',
        'secondary-fixed-dim': '#b9c7df',
        'surface-dim': '#d8dadc',
        'on-background': '#191c1e',
        'surface-bright': '#f7f9fb',
        'outline-variant': '#c7c4d7',
        'surface-tint': '#5148d7',
        'secondary-fixed': '#d5e3fc',
        primary: '#2a14b4',
        'on-tertiary-container': '#bac5dd',
        'on-error-container': '#93000a',
        background: '#f7f9fb',
        'on-secondary-fixed-variant': '#3a485b',
        'on-primary-fixed-variant': '#372abf',
        surface: '#f7f9fb',
        'inverse-surface': '#2d3133',
        'error-container': '#ffdad6',
        'tertiary-container': '#475266',
        'on-secondary-fixed': '#0d1c2e',
        'inverse-primary': '#c3c0ff',
        'primary-fixed': '#e3dfff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        base: '4px',
        xs: '4px',
        md: '16px',
        sm: '8px',
        'max-width': '1200px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter'],
        'headline-md': ['Inter'],
        'mono-sm': ['Geist'],
        'body-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'label-md': ['Inter'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'mono-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      maxWidth: {
        'max-width': '1200px',
        'screen-xl': '1200px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
